tategakibunko/jingoo

- src/jg_interp.ml
- src/jg_parser.mly
- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
- tests/test_output.ml
This enables you to write `obj[expr]` where `expr` should evaluate to a `Tstr`.  I find this to be useful, and you can also do it with Jinja2.
> Allow for expressions in object lookup

- Makefile
- opam
- src/Makefile
Hi,
First, thanks for this great library! We use it a lot @cryptosense to generate all kinds of HTML reports.
Some environments do not support native compilation. This adds a "make byte" target that only builds a bytecode library. This target is automatically selected by opam when the variable `ocaml-native` is false.
Thanks!
> Add a bytecode-only target

- Makefile
- example/Makefile
- src/Makefile
- tests/Makefile
For compatiblity with systems that do not ship with GNU make by default, including *BSDs and OS X.
Closes #16.
> use $(MAKE) instead of hard-coded make

- src/Makefile
Since OCaml 4.03, the compiler can use .cmx files to perform cross-module optimization. A side effect of this is that if these files are not installed and the corresponding .cmi file is not compiled with `-opaque`, the following warning is printed:
```
Warning 58: no cmx file was found in path for module Jg_template, and its interface was not compiled with -opaque
```
This fixes this warning and makes it possible to get extra optimizations.
Thanks! ✨
> Install .cmx files

- example/cheatsheet.tmpl
- example/test_data.ml
- src/jg_runtime.ml
The patch adds support for iterating over Tobj and Thash data types passed via the OCaml API
> Add support for iterating over Tobj and Thash data type passed from OCaml

- src/jg_utils.ml
Note that this implies that ocaml < 4.02 may not be supported without
some hack as `really_input_string` was introduced in 4.02.0.
> Adapt to OCaml's 4.06.0 where -safe-string is the default.

- src/jg_interp.ml
- src/jg_runtime.ml
- src/jg_template.ml
- src/jg_template.mli
- src/jg_types.ml
- src/jg_types.mli
- src/jg_utils.ml
- tests/test_runtime.ml
/!\ This is a breaking change for user using *internal* functions from but this is transparent for user using `Jg_template` module (except the extra optional parameter for `Jg_template.from_file function`.
This output parameter give me a good performance improvement on my web server since I avoid an unnecessary buffer while printing my page.
> Generic output

- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
Also:
* avoid unnecessary list construction (use List.fold_left2 instead of List.fold_left + List.combine)
* used String.trim (ocaml 4.00.0) instead of Pcre.replace
> Added Tlazy constructor.

- example/cheatsheet.tmpl
- example/test_data.ml
- src/jg_interp.ml
- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
- tests/test_output.ml
First, I can split this into two PR if you want, but if you like the whole stuff it is simpler to make only one.
`Tvolatile` use case is to access some `mutable` field of a structure, or a `ref` that could evolve between the time the data are built and the time the template is evaluated.
Also, I fixed the order of evaluation of `and` and `or` expressions.
`jg_and (value_of_expr env ctx left) (value_of_expr env ctx right)` make both `left` and `right` sides evaluated. Also, OCaml evaluate function's arguments from right to left), so the right side of the test would be evaluated first here. This was not my main concern, but it could lead to unexpected behavior if some side effect is involved in `left` and `right`.
The main problem was that `{% if foo && foo.bar %}` would raise an exception …
>  Added Tvolatile contructor + few fixes

- src/jg_lexer.mll
- src/jg_runtime.ml
- src/jg_utils.ml
- tests/test_runtime.ml
As I am a little bit concerned by rendering speed, I would like to be able to avoid most of `Pcre` calls. And mostly the ones that are likely to occur often.
I may have changed since 2011 (also, it may not) but according to https://mirage.io/blog/ocaml-regexp, Pcre is not fast at all.
Most of the `Pcre` could be replaced quite easily by vanilla OCaml without adding to much lines/complexity to the code.
`jg_urlize` is probably the more tricky function to re-implement without a regexp lib, because I did not really looked at what this regexp is supposed to done.
Any comment?
Note to myself jinja2 implementation: https://github.com/pallets/jinja/blob/f2e9280f5e5a4e753edb33415f9a16e56b20562a/jinja2/utils.py#L189
> Optimize some operations on strings

- example/cheatsheet.tmpl
- src/jg_interp.ml
- src/jg_parser.mly
- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
As it is said in http://jinja.pocoo.org/docs/2.10/templates/#assignments
```
As of version 2.10 more complex use cases can be handled using namespace objects which allow propagating of changes across scopes:
{% set ns = namespace(found=false) %}
{% for item in items %}
{% if item.check_something() %}
{% set ns.found = true %}
{% endif %}
* {{ item.title }}
{% endfor %}
Found item having something: {{ ns.found }}
Note hat the obj.attr notation in the set tag is only allowed for namespace objects; attempting to assign an attribute on any other object will raise an exception.
New in version 2.10: Added support for namespace objects
```
NB: My implementation *may* be bugged because it does not allow you to access variables from outside of your current `{% block %}` section. I am not sure if …
> Added basic namespace support.

- src/jg_parser.mly
- tests/test_output.ml
`{% if something %}aaa{% else %}{% endif %}` used to work in 1.2.17, but broke in 1.2.18. This fix restores backwards compatibility.
> Add support for empty else and a test for it

- .gitattributes
- src/jg_parser.mly
Note: syntax highlighting will not work until .jingoo file changes, but I tried to push some dummy changes and it worked.
> Added .gitattribute to provide .jingoo syntax highlight on github.

- src/jg_cmdline.ml
- src/jg_interp.ml
- src/jg_lexer.mll
- src/jg_runtime.ml
- src/jg_template.ml
- src/jg_template.mli
- src/jg_types.ml
- src/jg_types.mli
- tests/test_runtime.ml
Summary of these improvements:
- `function` and `eval`: avoid useless buffering and marshaling of values andreturn the last value only. Previous implementation returned the first value only, but this one is more consistent with OCaml, and functions/eval must return only one value anyway.
- Added some filters: `nth` `forall`
- Support array/list appending with the `+` operator. Consistent with the fatch that it already is a multi-purpose operateur used to concat strings.
- Some fixes in the lexer (whitespace control and empty text at the end of parsing) and better error messages.
- Regex: switched from `Re.Pcre` to `Re.Str` so we can use groups in the replacement string.
- Fixed `jg_cmdlin` and include `jingoo` binaray in installation.
- Rework of `attr` filter
- Fixed `jg_slice` (which is …
> Some enhancements

- example/samples/for.jingoo
- example/test.ml
- src/jg_cmdline.ml
- src/jg_interp.ml
- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
- src/jg_utils.ml
- tests/test_output.ml
- tests/test_runtime.ml
This is how my idea for making partial application works for any functions, looks like.
I also created helpers to get rid of the unused kwargs in filters definition.
As I said, `loop.cycle ("even", "odd")` would become `loop.cycle (["even", "odd"])` but that's the only breaking change.
Also, if I read the code correctly `(fn ("x"))(arg="foo", "y")` was interpreted as `fn ("x", "y")` and should now be interpreted as `fn ("x", arg="foo", "y")`
> Reworked Tfun to provide partial application for all functions.

- src/jg_runtime.ml
- tests/test_runtime.ml
In real world, it is likely to find this kind of input: `Bla bla bla (see http://some.url) bla bla`.
While `http://some.url)` seems to be a valid url, this is probably not want you want, so I chose to include `)` `]` and `}` only if an opening character has been parsed.
Also, as urls between quotes are likely to be html attributes, we do not turn them into a link.
> Improved jg_urlize_regexp for real-world usage.

- dune-project
- example/samples/is.jingoo
- example/test.ml
- jingoo.opam
- src/dune
- src/jg_ast_mapper.ml
- src/jg_ast_optimize.ml
- src/jg_interp.ml
- src/jg_lexer.mll
- src/jg_parser.mly
- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
- tests/test_dead_code_elimination.ml
- tests/test_output.ml
- tests/test_runtime.ml
First choice is to switch to menhir instead of ocamlyacc. menhir is just better thant ocamlyacc, and it helped me a lot for reducing the number of conflicts and simplify the writing of rules. I think it totally worth it to add this as a new dependency.
Some `tvalue` unwrapping:  `ForStatement`, `FromImportStatement`, `CallStatement`, `WithStatement` and `ApplyExpr` now uses strings (ident) values instead of tvalues + unwrapping. 
`KeywordExpr` and `AliasExpr` removed from `Jg_types.expression` as they were not really expressions but juste useful for some cases (e.g. macro/function definition/application).
As a side effect, it may avoid the parser to accept programs that will be rejected at runtime, see the removal of `expr -> failwith @@ spf "syntax error: value_of_expr:%s" …
> Parser enhancement, tvalue unwrapping.

- example/samples/macro.jingoo
- example/templates/templates.en.jingoo
- src/jg_parser.mly
I use to add a comment at the end of my macros, so I do not have to jump to the `{% macro ... %}` statement to remember the name of what I am looking at when it does not fit in one screen. It might help to allow the `endmacro` to take the name of the macro being defined as label.
It can also be used as an extra security to be sure to be closing the good macro.
> Allow repeating macro name in endmacro part.

- src/jg_parser.mly
This would fix a problem where.
```
{% switch foo %}
{% case 1 %}
```
would fail.
You actually need to use
```
{% switch foo %}
{%- case 1 %}
```
or
```
{% switch foo -%}
{% case 1 %}
```
Nothing should appear between `SWITCH` and `CASE` because it makes no sens.
That being said, I am not sure if jingoo should automatically trim the user input or fail with a comprehensible error message so the user can easily fix its input.
> Parser: auto trimming TEXT just after SWITCH token.

- src/jg_interp.ml
- src/jg_runtime.ml
- src/jg_types.ml
- tests/test_runtime.ml
<strike>
```jinja2
{% macro aux (x) %}
{% set ns = namespace (mark='') %}
<li><ul>
{% for x in x %}
{% set ns.mark += 'x' %}
<li>{{ ns.mark }} {{ x.name }}: {{ x.value }}</li>
{% endfor %}
</li></ul>
{% endmacro %}
{%- set ns = namespace (cnt = 0) -%}
<ul>
{%- for g in list -%}
{{ aux (g) }}
{%- set ns.cnt = ns.cnt + 1 -%}
{%- endfor-%}
</ul>
<p>Number of elements: {{ ns.cnt }}</p>
```
The last line will produce `<p>Number of elements: </p>`.
Current implementation silently erase any existing namespace, which is likely to produce very strange errors in case of nested macro/function calls.
This PR propose to disallow this, because it is really likely to: at best create errors, at worst corrupt or leak data.
A failure is now raised to prevent this an make the author correct its namespace …
> Improved error messages.

- jingoo.opam
See ocaml/opam-repository#15508 - without this, builds of jingoo might try to build outside of opam's sandbox.
> Update opam's build instructions

- example/samples/set_block.expected
- example/samples/set_block.jingoo
- example/templates/templates.en.jingoo
- example/test.ml
- src/jg_ast_mapper.ml
- src/jg_ast_optimize.ml
- src/jg_interp.ml
- src/jg_lexer.mll
- src/jg_parser.mly
- src/jg_runtime.ml
- src/jg_types.ml
- src/jg_types.mli
This matches jinja2 2.8's {% set variable %}block of data{% endset %}.
> Add support for capturing a block's output into a variable.

- example/samples/function.expected
- example/samples/function.jingoo
- example/samples/macro.expected
- example/samples/macro.jingoo
- src/jg_interp.ml
- src/jg_runtime.ml
This will cause us to raise if
- a macro receives more anonymous arguments than it expects
- a macro receives a keyword argument that it does not expect
This helps people that move over from jinja2 to not have their
templates silently misbehave where they used to pass in positional
arguments for arguments that are defined with a default value.
e.g.
{% macro test(a=False, b=False) %} ... {% endmacro %}
{{ test(True, True) }}
> Raise errors when macro gets called with unknown arguments.

- src/jg_interp.ml
- src/jg_template.ml
- src/jg_template.mli
Add a new module to the Jg_template interface which allows one to
store a parsed template in memory so it can be evaluated multiple
times against different models more efficiently.
> Interface for loading templates for multiple evaluations.

- src/jg_runtime.ml
This is insignificant, but it is useless to use add instead of replace.
> jg_init_context: used Hashtbl.replace instead of add so you won't waste space

- src/jg_interp.ml
- src/jg_parser.mly
Add support for `{% set ns [ k ] = x %}` which is the same as `{% set ns.k = x %}` but with `k` being an expression instead of a string.
I use it to use namespaces as hash tables, I do not know if is it hackish of it is a real feature.
It probably won't help a lot, but this is a code I actually use in order to traverse a data structure and build some kind of index.
```jingoo
{%- set RELATION_CHOICE_NS = namespace () -%}
{%- for m in M.data -%}
{%- for p, n in m.data -%}
{%- if p.first_name != "?" && p.surname != "?" -%}
{%- set x = RELATION_CHOICE_NS [p.iper] -%}
{%- if x -%}
{%- set RELATION_CHOICE_NS [p.iper] =
[ x[0], x[1] + 1,   x[2],  x[3]
, (m.x1 && not (m.x1 in x[4]) ? [m.x1] + x[4] : x[4])
, (m.x2 && not (m.x2 in x[5]) ? [m.x2] + x[4] : x[5]) ] -%}
{%- else -%}
{%- set …
```
> Set statement

- src/jg_runtime.ml
- src/jg_utils.ml
- tests/test_runtime.ml
I didn't find the urlencode filter necessary for Mapping format data, so it still only supports strings and iterables.
> implemented urlencode for str, iterable(mapping is not yet)

- src/jg_types.mli
The deriving argument has no effect in a signature.
This was revealed by https://github.com/ocaml/opam-repository/pull/25458#issuecomment-1992006886.
> Remove unnecessary `with_path` argument from deriving show in signature
